version: "3.1"

services:
  ux:
    image: react-flippy
    container_name: ux
    ports:
      - "3000:3000"
    build: ./client
    volumes:
      - ./client:/app
  api:
    image: express-docker
    container_name: api
    ports:
      - "8080:8080"
    build: ./server
    volumes:
      - ./server:/app