import { Position } from 'reactflow'

export const initialNodes = [
  {
    id: "1",
    position: { x: 270, y: 0 },
    data: { label: "Alpha", resizable: true, rotatable: true },
    type: "resizeRotate",
    targetPosition: Position.Top,
    sourcePosition: Position.Bottom,
    selected: false,
    style: { width: 100, height: 100 },
  },
  {
    id: "2",
    position: { x: 270, y: 100 },
    data: { label: "Bravo", resizable: true, rotatable: true },
    type: "resizeRotate",
    targetPosition: Position.Top,
    sourcePosition: Position.Bottom,
    selected: false,
    style: { width: 100, height: 100 },
  },
  {
    id: "3",
    position: { x: 100, y: 200 },
    data: { label: "Charlie", resizable: true, rotatable: true },
    type: "resizeRotate",
    targetPosition: Position.Top,
    sourcePosition: Position.Bottom,
    selected: false,
    style: { width: 100, height: 100 },
  },
  {
    id: "4",
    position: { x: 425, y: 200 },
    data: { label: "Delta", resizable: true, rotatable: true },
    type: "resizeRotate",
    targetPosition: Position.Top,
    sourcePosition: Position.Bottom,
    selected: false,
    style: { width: 100, height: 100 },
  },
  {
    id: "5",
    position: { x: 20, y: 300 },
    data: { label: "Echo", resizable: true, rotatable: true },
    type: "resizeRotate",
    targetPosition: Position.Top,
    sourcePosition: Position.Bottom,
    selected: false,
    style: { width: 100, height: 100 },
  },
  {
    id: "6",
    position: { x: 180, y: 300 },
    data: { label: "Foxtrot", resizable: true, rotatable: true },
    type: "resizeRotate",
    targetPosition: Position.Top,
    sourcePosition: Position.Bottom,
    selected: false,
    style: { width: 100, height: 100 },
  },
  {
    id: "7",
    position: { x: 350, y: 300 },
    data: { label: "Golf", resizable: true, rotatable: true },
    type: "resizeRotate",
    targetPosition: Position.Top,
    sourcePosition: Position.Bottom,
    selected: false,
    style: { width: 100, height: 100 },
  },
  {
    id: "8",
    position: { x: 510, y: 300 },
    data: { label: "Hotel", resizable: true, rotatable: true },
    type: "resizeRotate",
    targetPosition: Position.Top,
    sourcePosition: Position.Bottom,
    selected: false,
    style: { width: 100, height: 100 },
  },
];

export const initialEdges = [
  { id: "1-2", source: "1", target: "2", label: "foo", type: "smoothstep" },
  { id: "2-3", source: "2", target: "3", label: "bar", type: "smoothstep" },
  { id: "2-4", source: "2", target: "4", label: "baz", type: "smoothstep" },
  { id: "3-5", source: "3", target: "5", label: "bing", type: "smoothstep" },
  { id: "3-6", source: "3", target: "6", label: "buzz", type: "smoothstep" },
  { id: "4-7", source: "4", target: "7", label: "spam", type: "smoothstep" },
  { id: "4-8", source: "4", target: "8", label: "eggs", type: "smoothstep" },
];